--creating table

create table Revenue(
City nvarchar(30),
TotalRevenue int
);

--Sp 
--O/P: Revenue generated by each sales territory
Go

create procedure geteachsaleRevenue
as
begin
truncate table Revenue;
insert into Revenue (City, TotalRevenue)

	select a.city, SUM(sod.OrderQty * (sod.UnitPrice-
	sod.UnitPriceDiscount)) as TotalRevenue

	from SalesLT.SalesOrderDetail sod
	join SalesLT.SalesOrderHeader soh on

	soh.SalesOrderID=sod.SalesOrderID

	join SalesLT.CustomerAddress ca on

	ca.CustomerID=soh.CustomerID

	join SalesLT.Address a on a.AddressID = ca.AddressID
	group by a.City;

end

--calling sp
go
exec geteachsaleRevenue;

--displaying the result
select * from Revenue;